### ISSUE TITLE
app启动太慢

### ISSUE THREAD

**Issue by Sujie1** [AriesHoo/FastLib#1]
app启动太慢的原因是什么

**Comment by AriesHoo** [comment]
可以再描述清楚些吗？是我的Demo吗？一般app启动过慢主要是在主进程做了太多操作造成的延时。我的demo主要做效果的演示未做相应的优化操作。具体的需要在自己应用中优化

**Comment by AriesHoo** [comment]
我今天测试了下我在Application里初始化配置耗时30ms算是正常耗时。你自己校验下是否在application里做了过多的耗时操作

**Comment by Sujie1** [comment]
嗯 我再检查一下我的项目吧
