### ISSUE TITLE
在ConstraintLayout 布局中,TitleBarView 会被压缩

### ISSUE THREAD

**Issue by bing27** [AriesHoo/FastLib#24]
请教下,该如何处理

**Comment by bing27** [comment]
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="wbb.android.activity.iii_demo.ExpandableListViewActivity">

    <include
        android:id="@+id/titleBar_headFastLib"
        layout="@layout/fast_layout_title_bar" />

    <ExpandableListView
        android:id="@+id/elv"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_constraintTop_toBottomOf="@id/titleBar_headFastLib" />

</android.support.constraint.ConstraintLayout>

**Comment by AriesHoo** [comment]
使用库版本多少，截图看看效果？

**Comment by bing27** [comment]
![tx](https://user-images.githubusercontent.com/23740845/53308215-5d3fd080-38da-11e9-8475-4b91c52efe98.jpg)

**Comment by bing27** [comment]
只要做操作了, 就会发生

**Comment by AriesHoo** [comment]
ConstraintLayout 下使用，确实在部分情况会出现测量问题，目前还未发现解决方案，可先使用LinearLayout代替下，找到解决方案后通知你

**Comment by AriesHoo** [comment]
你是库用的多少版本？手机系统版本多少？我这用ConstraintLayout点击没有出现你那种情况

**Comment by bing27** [comment]
最新的版本也是,我在博主的项目里运行也出现

**Comment by bing27** [comment]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <include layout="@layout/fast_layout_title_bar" />

    <com.aries.ui.view.radius.RadiusTextView
        android:id="@+id/rtv1"
        android:layout_width="match_parent"
        android:layout_height="40dp"
        app:layout_constraintTop_toTopOf="parent"
        android:layout_marginTop="100dp"
        android:text="QQ样式" />

    <com.aries.ui.view.radius.RadiusTextView
        android:id="@+id/rtv2"
        android:layout_width="match_parent"
        android:layout_height="40dp"
        android:text="banner样式"
        app:layout_constraintTop_toBottomOf="@id/rtv1" />

    <com.aries.ui.view.radius.RadiusTextView
        android:id="@+id/rtv3"
        android:layout_width="match_parent"
        android:layout_height="40dp"
        android:text="PullScrollView"
        app:layout_constraintTop_toBottomOf="@id/rtv2" />

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by AriesHoo** [comment]
稍等，我这边试一试

**Comment by bing27** [comment]
![1](https://user-images.githubusercontent.com/23740845/53391045-17fdca80-39d0-11e9-9c8c-21fb1a2a5a7a.jpg)

**Comment by bing27** [comment]
![2](https://user-images.githubusercontent.com/23740845/53391151-66ab6480-39d0-11e9-82aa-47ea295c9582.jpg)

**Comment by AriesHoo** [comment]
我知道了。。这个是华为这种导航栏可以开关系统上差异，我找找原因

**Comment by bing27** [comment]
其他手机 也有,比如vivo

**Comment by AriesHoo** [comment]
是不是都是有虚拟导航栏那种的？

**Comment by bing27** [comment]
不是,vivo 没有虚拟的

**Comment by AriesHoo** [comment]
我这边复现了。找下解决方案

**Comment by AriesHoo** [comment]
TitleBarView在ConstraintLayout中高度测量有问题，目前没找到原因所在。
解决方案
一:不使用ConstraintLayout 
二 使用ConstraintLayout 不使用TitleBarView  使用如果少的话使用xml 定义TitleBarView 并配合StatusBarViewHelper适配沉浸式

后续找到原因再更新

**Comment by AriesHoo** [comment]
implementation 'com.github.AriesHoo.UIWidget:widget-core:3.2.8.1'
使用这个版本库，不过还是建议
ConstraintLayout与TitleBarView 不同时使用
