### ISSUE TITLE
自己定义继承FragmentActivity的类，在5.0系统及以下会闪退

### ISSUE THREAD

**Issue by wuwenlin** [AriesHoo/FastLib#26]
闪退原因Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content

**Comment by AriesHoo** [comment]
使用库版本多少？百度过错误原因没有？

**Comment by wuwenlin** [comment]
我是自己把demo的代码下载下来进行依赖的，有百度过，我就是想问下你的库有没有在Activity的onCreate方法中调用requestWindowFeature方法呢？因为报这个错误说是requestWindowFeature调用的位置不正确

**Comment by AriesHoo** [comment]
全局搜了一下，貌似没有

**Comment by wuwenlin** [comment]
好的，谢谢
