### ISSUE TITLE
FastLifecycleCallbacks

### ISSUE THREAD

**Issue by wuwenlin** [AriesHoo/FastLib#27]
FastLifecycleCallbacks这个类对自定义的FragmentActivity里有requestWindowFeature这个方法会闪退报requestFeature() must be called before adding content

**Comment by AriesHoo** [comment]
你使用的是哪个版本，我这真的全局搜索没有requestWindowFeature且，在FastLifecycleCallbacks页面单独搜索也没有requestWindowFeature

**Comment by wuwenlin** [comment]
那这个类要是没有继承有影响吗

**Comment by AriesHoo** [comment]
不影响，这个类是库内注册的生命周期监听

**Comment by wuwenlin** [comment]
好的，谢谢
