### ISSUE TITLE
AccessibilityDelegate 这个类不可用

### ISSUE THREAD

**Issue by flowvwrvvsv** [AriesHoo/FastLib#28]
java.lang.NoClassDefFoundError: cn.bingoogolapple.swipebacklayout.BGASwipeBackLayout$AccessibilityDelegate

我用这个库的时候，为啥会有这个错误

**Comment by AriesHoo** [comment]
1、使用的多少版本的库？
2、是否运行demo？demo是否出错？
3、测试得系统是否为5.0以下，是否配置分包？

**Comment by AriesHoo** [comment]
还有就是最新版本2.2.12 使用的androidx项目是否做相应配置

**Comment by flowvwrvvsv** [comment]
你好，谢谢你，我正被这个搞得头大
1demo运行没有问题，
2测试手机是6.0系统
3我用的是support1.0.0
4我用的你的library，
![image](https://user-images.githubusercontent.com/16237147/53936332-715aad80-40e4-11e9-8be2-1ddb8098d274.png)

**Comment by AriesHoo** [comment]
是否没有配置Androidx，可以使用**Android Studio** 带的**Refactor->Migrate to AndroidX**功能,或者参看文章 https://blog.csdn.net/qq_17766199/article/details/81433706

**Comment by flowvwrvvsv** [comment]
刚才的问题解决了，但是又是同样的一个错误出现了，我感觉可能是手机的问题，我用的华为麦芒4 
![image](https://user-images.githubusercontent.com/16237147/53938628-c2ba6b00-40eb-11e9-98ed-d239ea4a0df4.png)

**Comment by AriesHoo** [comment]
检查下是否未设置分包？或者直接在我的demo上修改

**Comment by flowvwrvvsv** [comment]
我是把你的library导入到新项目里面来的，应该没有使用分包的情况

**Comment by AriesHoo** [comment]
你配置下看样子像是分包问题

**Comment by flowvwrvvsv** [comment]
恩恩，我也查了感觉好像必须要分包才行

**Comment by flowvwrvvsv** [comment]
但是你的Demo项目中也未使用分包啊

**Comment by AriesHoo** [comment]
我设置minSdkVersion 21 然后gradle配置的

**Comment by flowvwrvvsv** [comment]
你gradle有配置分包吗，我把library导入过来就没有改动过，app包的gradle也是模仿你的在配置
![image](https://user-images.githubusercontent.com/16237147/54002966-76bf0300-418b-11e9-9b12-c3efe5a4a212.png)
![image](https://user-images.githubusercontent.com/16237147/54002993-8b030000-418b-11e9-968a-ab7b8e7e274a.png)

**Comment by flowvwrvvsv** [comment]
你好上面的问题已经解决，我在gradle导入了和你app的相同的包，就没有报这个错误了

**Comment by AriesHoo** [comment]
解决了就好
