### ISSUE TITLE
底部虚拟键

### ISSUE THREAD

**Issue by flowvwrvvsv** [AriesHoo/FastLib#29]
你好，这个项目的底部虚拟键咋会是透明的

**Comment by AriesHoo** [comment]
我做的沉浸式处理   请看[wiki](https://github.com/AriesHoo/FastLib/wiki#415-navigationviewhelper-%E5%AF%BC%E8%88%AA%E6%A0%8F%E6%B2%89%E6%B5%B8%E5%B8%AE%E5%8A%A9%E7%B1%BB)
