### ISSUE TITLE
为什么现在不能直接全局配置是否加载动画

### ISSUE THREAD

**Issue by Sujie1** [AriesHoo/FastLib#3]

**Comment by AriesHoo** [comment]
可否告知你之前使用的那个版本？现在使用的哪个版本？

**Comment by AriesHoo** [comment]
请参考最新版本AppImpl 里
 /**
     * Adapter加载更多配置
     *
     * @param adapter
     * @return
     */
    @Nullable
    @Override
    public LoadMoreView createDefaultLoadMoreView(BaseQuickAdapter adapter) {
        if (adapter != null) {
            //设置动画是否一直开启
            adapter.isFirstOnly(false);
            //设置动画
            adapter.openLoadAnimation(BaseQuickAdapter.SCALEIN);
        }
        //方式一:设置FastLoadMoreView--可参考FastLoadMoreView.Builder相应set方法
        //默认配置请参考FastLoadMoreView.Builder(mContext)里初始化
        return new FastLoadMoreView.Builder(mContext).build();

里不操作 adapter 相应设置动画属性即可。
