### ISSUE TITLE
implement

### ISSUE THREAD

**Issue by flowvwrvvsv** [AriesHoo/FastLib#31]
implementation 'com.github.AriesHoo:FastLib:2.2.12'

你好使用这种方式导入，打包的时候有问题啊
![image](https://user-images.githubusercontent.com/16237147/54736705-67a66f00-4be7-11e9-9b30-76e9f8eae59a.png)

**Comment by AriesHoo** [comment]
那你使用本地module嘛

**Comment by flowvwrvvsv** [comment]
。。。你得意思是导入module嘛？我之前用的本地module，我想着用这个方式可以一直更新你的项目。。。

**Comment by AriesHoo** [comment]
网上说貌似是有库冲突 https://blog.csdn.net/dubo_csdn/article/details/81743397

**Comment by flowvwrvvsv** [comment]
我去试试

**Comment by flowvwrvvsv** [comment]
![image](https://user-images.githubusercontent.com/16237147/54737301-2cf20600-4bea-11e9-8425-2b959db5c231.png)
你好这个问题已经解决了， 删除这一行就可以了，你的项目里面已经有这个东西所以会冲突，

**Comment by AriesHoo** [comment]
ok，我使用的的是Androidx

**Comment by flowvwrvvsv** [comment]
但是有个问题，我如果在app项目想用appcompat-v7这里面的东西怎么办？

**Comment by AriesHoo** [comment]
一样的，Android studio会相互转换的，只要不同时使用即可

**Comment by flowvwrvvsv** [comment]
有个问题，我的app工程依赖你的项目，你项目中所有的包我都可以使用么

**Comment by flowvwrvvsv** [comment]
我以前就遇到过这种问题，依赖了其他项目A，项目A依赖了项目B，我在主项目工程里面却不能使用项目B中的代码，，，我是以本地MOdule的方式导入的

**Comment by AriesHoo** [comment]
那可能项目b的引入模式只能给a使用

**Comment by flowvwrvvsv** [comment]
难道开发Android Studio 的工程师没想到这个问题，不应该啊!..!

**Comment by AriesHoo** [comment]
https://majing.io/posts/10000007081192 了解下

**Comment by flowvwrvvsv** [comment]
感觉从你的项目中可以了解到很多最新的项目，厉害呀，，，，

**Comment by AriesHoo** [comment]
这些也不算新项目，都比较流行的

**Comment by flowvwrvvsv** [comment]
我有一年多没搞Android了，你的项目也是在GitHub上偶然看到的，一直在跟

**Comment by AriesHoo** [comment]
咋又回坑了？欢迎回坑

**Comment by flowvwrvvsv** [comment]
哈哈哈，一直都在坑里，之前受伤了，就一直没搞，上次我说的那个通用的那个请求，我去把retrofit下载源码改了，

**Comment by flowvwrvvsv** [comment]
然后各种报错，一看又要改rxJava的方法的，我就放弃了

**Comment by AriesHoo** [comment]
感觉不能那么弄的。事件处理流程都不是那么走的

**Comment by flowvwrvvsv** [comment]
我再试试看看，我感觉不是事件的流程问题，应该是反射确定类型的时候无法判断，看看有没有其他方式

**Comment by flowvwrvvsv** [comment]
我现在用的implement的方式导入，还是回出现这种错误。。。
![image](https://user-images.githubusercontent.com/16237147/54744195-3dfa4180-4c01-11e9-82ec-899a04a103b7.png)

**Comment by AriesHoo** [comment]
这怕是分包问题吧

**Comment by flowvwrvvsv** [comment]
必须要把这个加上才不会报错，不管是本地Model方式导入，还是Githup方式导入
![image](https://user-images.githubusercontent.com/16237147/54744505-1fe11100-4c02-11e9-9ee3-31173db34256.png)

**Comment by AriesHoo** [comment]
这个是刷新头，必须要加

**Comment by flowvwrvvsv** [comment]
但是在你的library里面是已经导入了的，为啥app主项目里面找不到。。。

**Comment by AriesHoo** [comment]
![image](https://user-images.githubusercontent.com/19605922/54744768-c6c5ad00-4c02-11e9-8c3b-976c67a60771.png)

**Comment by flowvwrvvsv** [comment]
你好在吗，请问我Scroll View里面包裹了几个Edit TExt为什么点击的时候EditText下面的布局回消失？

**Comment by AriesHoo** [comment]
布局咋样的？效果图咋样的？猜测不是消失 了。应该是滚动到下边了。你滚动试一试

**Comment by flowvwrvvsv** [comment]
外层是Scroll View，滚不动，KeyBordHelper点击软键盘以外，软键盘就消失了
![微信图片_20190325155735](https://user-images.githubusercontent.com/16237147/54903391-bcfbbc80-4f16-11e9-95e8-34096629021e.jpg)

**Comment by AriesHoo** [comment]
这种要让布局滚动吧，，如果你不想某个Activity 不控制软键盘可以在setNavigationBar 回调里将Activity过滤掉
help.setControlBottomEditTextEnable(!(activity insteadof xxx))

**Comment by flowvwrvvsv** [comment]
好，我研究一下

**Comment by flowvwrvvsv** [comment]
if里面的代码注释以后就没问题了，不知道为啥
![image](https://user-images.githubusercontent.com/16237147/54905253-8c6a5180-4f1b-11e9-965f-f527f176a2d8.png)

**Comment by AriesHoo** [comment]
那句代码就是 部分情况下控制软键盘功能的

**Comment by flowvwrvvsv** [comment]
那段代码的意思是不是，再新开的activity里面，如有又EditText有焦点，就会谈起软键盘？

**Comment by AriesHoo** [comment]
你可以进去看下。。setEnable 里面咋处理的

**Comment by flowvwrvvsv** [comment]
1 我把调用setEnable注释以后，就不会出现EditText下面的布局消失的问题，
2 setEnable方法添加了adjustSpan和adjustReszie，还有添加了全局的GlobalLayoutListener，但是我还是没找到弹出软键盘时，界面控制的代码。。。求解惑

**Comment by flowvwrvvsv** [comment]
找到了

**Comment by AriesHoo** [comment]
onGlobalLayoutListener里通过setPadding 来留出软键盘高度

**Comment by flowvwrvvsv** [comment]
1 这个是先等待软键盘弹出以后才设置padding的吗？
2 界面上 软键盘的高度是始终不变的，bottomPadding也应该再变才行吧
个人理解
![image](https://user-images.githubusercontent.com/16237147/54909640-a872f080-4f25-11e9-9167-6a539d868975.png)

**Comment by AriesHoo** [comment]
这个是软键盘开关都会设置padding，而且确实是变化的

**Comment by flowvwrvvsv** [comment]
我debug看了下，每次的paddinBottom是一样的，那还是不行哦

**Comment by flowvwrvvsv** [comment]
我还想改改代码呢，发现是githup上的，改不了。。。

**Comment by AriesHoo** [comment]
哪里有问题？

**Comment by flowvwrvvsv** [comment]
我的意思是，paddingBottom不需要设置太高，editText下面的部分被隐藏掉了
![image](https://user-images.githubusercontent.com/16237147/54964408-583c7280-4fa7-11e9-94cd-44f9c9c6dcfe.png)

**Comment by AriesHoo** [comment]
这个paddingBottom是由根布局的paddingBottom和软键盘高度决定的，。正常的都是要滚动的。这个做的是一个通用场景，如果要单独处理，就关闭软键盘那段处理即可

**Comment by AriesHoo** [comment]
如果你的项目需求是不要管软键盘遮挡问题，可以关掉那段代码

**Comment by AriesHoo** [comment]
那个软键盘处理类是一个通用处理方案解决大多数应用场景，如果你要根据你这个需求去改变那个KeyboardHelper 的paddingBottom这个通用性就会被打破，更多的情况就会出问题

**Comment by AriesHoo** [comment]
根据你页面的效果来看，。这个是需要添加滚动ScrollView的。不然必然输入框会被软键盘遮住

**Comment by flowvwrvvsv** [comment]
我感觉是不是paddBottom的值太多了，
1 有个疑惑，我的那个界面有很多个editText，不管点击哪个edittext都会把当前点击的edittext置于顶部，
我看代码每次在填充的paddBottom都是同一个值

**Comment by flowvwrvvsv** [comment]
我代码最外层是nestScrollView
1 屏蔽软键盘的代码，如果editText太多，底部的editText就会被软键盘给遮挡住。。。

**Comment by flowvwrvvsv** [comment]
我还是感觉那个通用性，体验不怎么好呢

**Comment by AriesHoo** [comment]
这个见仁见智的。你也可以在那个帮助类基础上进行扩展以达到实际项目中的效果

**Comment by flowvwrvvsv** [comment]
代码是github上的改不了。。。

**Comment by AriesHoo** [comment]
一你已module集成修改 二 将代码拷贝下来。修改使用。。然后屏蔽掉FastLib的处理

**Comment by flowvwrvvsv** [comment]
1 有个疑惑，我的那个界面有很多个editText，不管点击哪个edittext都会把当前点击的edittext置于顶部，
我看代码每次在填充的paddBottom都是同一个值，按照我的理解点击不同位置edittext，paddBottom应该不同

**Comment by AriesHoo** [comment]
KeyBoardHelper原理为监听根布局GlobalLayoutListener 软键盘弹起根布局会变化回调，根据这个变化量（软键盘高度）来给根布局添加paddingBottom 故不管EditText。如果按照你所说还得在软键盘弹起监听当前focusView是否为EditText 且是否在软键盘下边遮住才进行处理，这样代价太大，你可以自己去试一试

**Comment by flowvwrvvsv** [comment]
嗯嗯好的，你的代码有这么一个效果，不管是点击哪个edittext，都会把点击的那个edittext顶到上面去，无论这个edittext被点击之前是在哪个位置，我是不明白这个东西，我在自己研究一下，不打扰你了

**Comment by flowvwrvvsv** [comment]
你好，FastRetrofit获取网络数据，gson数据转换成Date类型的时候，报时区异常错误

**Comment by flowvwrvvsv** [comment]
像这种的。
java.text.ParseException: Failed to parse date ["2019-04-10  10:16:48"]: Invalid time zone indicator ' ' (at offset 0)

请问你的FastRetrofit可以设置通用的时间解析么？

**Comment by AriesHoo** [comment]
这个好像是解析器的问题，你设置下解析器吧，一、这个本身就该后台接口返回正确的格式要么是时间戳，前端来格式化，要么把前端要展示的样式格式化好前端只显示格式化后的字符串即可 二、用String 接收 再自己转格式。建议第一种。给retrofit 设置多个解析器 FastRetrofit.getRetrofitBuilder().addCallAdapterFactory 一定要在设置了其它Retrofit配置后，在调用接口之前配置好 还是建议第一种方式

**Comment by flowvwrvvsv** [comment]
嗯，谢谢，我改了用String来接受就没事了，我主要想设置解析器这种，就是找不到入口，谢谢解惑

**Comment by AriesHoo** [comment]
这个东西本身就应该后台返回正常的格式。不要把简单得问题复杂化。 一个前端解析一次 n个就是n次。这是一种浪费。后台改一次所有调用接口的端全部解决，效率

**Comment by flowvwrvvsv** [comment]
嗯嗯，你说的对，我也觉得是这样的，我看了那个解析器，很麻烦。。。

**Comment by flowvwrvvsv** [comment]
你好，请问为什么Activity里面调用finish(), FastLifecycleCallbacks的onActivityDestroyed方法不回调，

**Comment by AriesHoo** [comment]
你是如何使用的，直接点击物理返回键会不会有相应回调。我这里测试是有相应回调的
![image](https://user-images.githubusercontent.com/19605922/56785186-90450880-6826-11e9-9177-3c6bbe9739f4.png)  
![image](https://user-images.githubusercontent.com/19605922/56785197-a0f57e80-6826-11e9-9f5b-cab464f507c6.png)

**Comment by flowvwrvvsv** [comment]
你好，依赖这个项目打包的时候，混淆需要注意什么问题呢

**Comment by AriesHoo** [comment]
混淆这块我还没有弄过，将FastLib 包下的类keep一下应该可以，

**Comment by William-SunShuo** [comment]
这个项目里设置全屏无效啊

**Comment by flowvwrvvsv** [comment]
![image](https://user-images.githubusercontent.com/16237147/59998890-249ae280-9693-11e9-8767-a1f8972a7404.png)
你好，请问这个TitleBarView 要怎么去掉下面的边线
![image](https://user-images.githubusercontent.com/16237147/59998938-3d0afd00-9693-11e9-83e8-92228331f63b.png)
我采用这种方式没哟效果

**Comment by AriesHoo** [comment]
你这个怕不是下划线，是加的海拔高度吧，你检查下是不有类似这样的代码ViewCompat.setElevation(titleBar, mContext.getResources().getDimension(R.dimen.dp_elevation));

**Comment by flowvwrvvsv** [comment]
哦哦，是的，找到了，谢谢了

**Comment by flowvwrvvsv** [comment]
你好请教一个问题，我用RadiusSwitch控件，在xml里面设置为true以后，第一次显示在界面上的还是灰色，要手动按下切换状态到false后，再按下切换到true才会变成绿色。
![image](https://user-images.githubusercontent.com/16237147/60750482-e0d1a280-9fdb-11e9-8d49-d3f6f285bdef.png)

**Comment by flowvwrvvsv** [comment]
我感觉这个控件会不会存在属性覆盖的问题，可能在xml里面设置的属性有效，但是加载出来以后会没效果

**Comment by AriesHoo** [comment]
确实存在你说的问题。实际使用还是没有问题。后面我看看是不是属性覆盖了，最近忙项目，没时间弄

**Comment by AriesHoo** [comment]
运行貌似正常的，就是预览有问题

**Comment by flowvwrvvsv** [comment]
开始我是这么觉得的，但是deletge是覆盖父类的方法，应该不会有属性覆盖的问题，流程上可能我还没发现具体的问题，我改用原生的switch了，这个自定义的这些view有啥学习的路径没，我感觉光看不练还是不行。

**Comment by yssmile** [comment]
你们2个聊天聊得好多哦，不知不觉间居然看完了，😃
