### ISSUE TITLE
全局配置的加载的FastLoadingDialog无法修改提示文字

### ISSUE THREAD

**Issue by renjunjia3** [AriesHoo/FastLib#32]

**Comment by AriesHoo** [comment]
你全局是咋设置的？你调用的地方咋写的

**Comment by renjunjia3** [comment]
全局配置：
CustomProgressLoadingDialog dialog = new CustomProgressLoadingDialog(activity);
        return new FastLoadDialog(activity, dialog)
                .setCancelable(true)
                .setCanceledOnTouchOutside(true);
自定义dialog的布局：

1. <?xml version="1.0" encoding="utf-8"?>
2. <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
3.     xmlns:app="http://schemas.android.com/apk/res-auto"
4.     android:id="@+id/loading"
5.     android:layout_width="wrap_content"
6.     android:layout_height="wrap_content"
7.     android:layout_gravity="center"
8.     android:background="@drawable/dialog_ffmpeg_loading_bg"
9.     android:gravity="center"
10.     android:minWidth="100dp"
11.     android:minHeight="100dp"
12.     android:orientation="vertical"
13.     android:padding="15dp">
14. 
15. 
16.     <com.timqi.sectorprogressview.ColorfulRingProgressView
17.         android:id="@+id/progressView"
18.         android:layout_width="40dp"
19.         android:layout_height="40dp"
20.         app:bgColor="#FDF0CB"
21.         app:fgColorEnd="@color/color_theme"
22.         app:fgColorStart="@color/color_theme"
23.         app:percent="0"
24.         app:startAngle="0"
25.         app:strokeWidth="3dp" />
26. 
27.     <TextView
28.         android:id="@+id/message"
29.         android:layout_width="wrap_content"
30.         android:layout_height="wrap_content"
31.         android:layout_marginTop="10dp"
32.         android:text="@string/processing"
33.         android:textColor="#414141"
34.         android:textSize="14sp" />
35. </LinearLayout>
36.

**Comment by AriesHoo** [comment]
![image](https://user-images.githubusercontent.com/19605922/56414338-d9440c80-62bc-11e9-9973-c56ddd50b5bb.png)
![image](https://user-images.githubusercontent.com/19605922/56414354-e3fea180-62bc-11e9-9a99-630726c17297.png)
![image](https://user-images.githubusercontent.com/19605922/56414366-ee20a000-62bc-11e9-9b19-5e49f2c29f33.png)

**Comment by AriesHoo** [comment]
也没见你哪里调用了setMessage方法啊。

**Comment by renjunjia3** [comment]
好了 我找到问题了
