### ISSUE TITLE
使用AutoSize没生效

### ISSUE THREAD

**Issue by sceneren** [AriesHoo/FastLib#33]
![image](https://user-images.githubusercontent.com/6612998/56794834-a57b6080-6841-11e9-894f-c798696b3450.png)
![image](https://user-images.githubusercontent.com/6612998/56794865-b5934000-6841-11e9-9366-75bc4aa63690.png)

**Comment by AriesHoo** [comment]
兄弟，你是不是抛出片场了

**Comment by sceneren** [comment]
...难受

**Comment by AriesHoo** [comment]
或者，你想达到啥效果，我帮忙想想

**Comment by sceneren** [comment]
![image](https://user-images.githubusercontent.com/6612998/56796106-71ee0580-6844-11e9-9237-f42b2436b1a4.png)
![image](https://user-images.githubusercontent.com/6612998/56796138-7ca89a80-6844-11e9-8683-5c8b6263ffc3.png)
![image](https://user-images.githubusercontent.com/6612998/56796161-86ca9900-6844-11e9-93d6-f897a5ab0569.png)
![image](https://user-images.githubusercontent.com/6612998/56796249-ba0d2800-6844-11e9-84c1-9315c1a94163.png)
大概代码就是上面那些要实现的效果
![image](https://user-images.githubusercontent.com/6612998/56796281-cbeecb00-6844-11e9-8879-537edfe515bf.png)
然后在小米4c上的效果：
![image](https://user-images.githubusercontent.com/6612998/56796360-f6d91f00-6844-11e9-9be0-63ea6cd53600.png)
pixel xl效果：
![image](https://user-images.githubusercontent.com/6612998/56796455-2425cd00-6845-11e9-93e3-ec84043848c2.png)
按理说效果是个是宽度刚好填满 但是效果却不是这样的。

**Comment by AriesHoo** [comment]
你是同时使用FastLib和AutoSize才出现适配问题的么？单独使用AutoSize就适配正常吗？我这库没有做适配相关代码，理论上不得有影响

**Comment by AriesHoo** [comment]
我这边也试一试

**Comment by AriesHoo** [comment]
小米6效果
![image](https://user-images.githubusercontent.com/19605922/56857001-e8e8e280-6999-11e9-95d7-508589b8cc18.png)
华为效果
![image](https://user-images.githubusercontent.com/19605922/56857004-028a2a00-699a-11e9-85c6-96c80d1a8664.png)
感觉我搞不定这个问题，得看AutoSize库作者的了。
