### ISSUE TITLE
刘海屏适配

### ISSUE THREAD

**Issue by sceneren** [AriesHoo/FastLib#34]
![5FA79B02E8804569B64E98511F896C69](https://user-images.githubusercontent.com/6612998/57423515-e2ceed80-7246-11e9-97cf-0e054d6bcc77.png)
![BAE4A20B1024BD2485C78873B19DC766](https://user-images.githubusercontent.com/6612998/57423524-ebbfbf00-7246-11e9-8d39-4464aca3ac26.png)
刘海屏没有做适配

**Comment by AriesHoo** [comment]
你这是哪款高端手机？国内手机貌似刘海都在状态栏的。我根据实际市场占有率考虑是否做相关视频

**Comment by sceneren** [comment]
pixel xl 开发者模式下调出来的

**Comment by AriesHoo** [comment]
国内的还没有哪款手机刘海超过状态栏吧

**Comment by sceneren** [comment]
一般是不会，只有先这样吧 。刚刚看来vivo的x21感觉没啥问题 但是还是很难受。可以参考下QMUI的实现。他的刘海适配就很不错。
![630CFDF631794D8431164472D17D7A1A](https://user-images.githubusercontent.com/6612998/57424095-0f840480-7249-11e9-91de-1f6bea3df10a.png)

**Comment by AriesHoo** [comment]
好呢，我参考下，如果合适我会尽快更新的，这个是在UIWidget库里的

**Comment by sceneren** [comment]
好的

**Comment by AriesHoo** [comment]
UIWidget 3.2.14版本已适配    implementation 'com.github.AriesHoo.UIWidget:widget-core:3.2.14'
