### ISSUE TITLE
问题。。

### ISSUE THREAD

**Issue by 1184104588** [AriesHoo/FastLib#35]
用你封装这个base,在没有用viewpager的时候 如何让一个fragment 点击重新走一次生命周期呢，相当于不缓存重新架加载。

**Comment by AriesHoo** [comment]
不太清楚你说的什么意思？不懒加载么？BasisFragment有一个变量mIsFirstShow 用于是否为第一次加载。可以在loadData里面设置mIsFirstShow =true以保证每次用户可见进行获取数据流程

**Comment by 1184104588** [comment]
对的。可以了 谢谢

**Comment by 1184104588** [comment]
对的。可以了 谢谢

**Comment by 1184104588** [comment]
对的。可以了 谢谢
