### ISSUE TITLE
minSdkVersion现在最低是21？

### ISSUE THREAD

**Issue by sceneren** [AriesHoo/FastLib#36]
能否兼容4.3 或者4.4的，项目有很多老年人用

**Comment by AriesHoo** [comment]
你用的哪个版本，我现在设置的是minLibSdkVersion = 15

**Comment by sceneren** [comment]
FastLib版本是2.2.13 我项目里面设置的是16 提示
Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.github.AriesHoo:FastLib:2.2.13] /Users/scene/.gradle/caches/transforms-2/files-2.1/9dc8bb5bc497c75a49725e608b020915/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.aries.library.fast" to force usage (may lead to runtime failures)

**Comment by AriesHoo** [comment]
![image](https://user-images.githubusercontent.com/19605922/61198324-0cefd080-a70c-11e9-8d83-cbe8b62168bb.png)

**Comment by AriesHoo** [comment]
我在beta版本里面改的

**Comment by sceneren** [comment]
好吧 那我替换为beta版本
