### ISSUE TITLE
项目中StatusLayoutManager好像没有效果,点击无反应

### ISSUE THREAD

**Issue by singlenoah** [AriesHoo/FastLib#38]
![图片](https://user-images.githubusercontent.com/16540388/62456239-94c87800-b7aa-11e9-8bd2-02f2eaf8ad8e.png)

**Comment by AriesHoo** [comment]
Demo只做简单演示。世纪项目需要自己配置
 @Override
    public void setMultiStatusView(StatusLayoutManager.Builder statusView, IFastRefreshLoadView iFastRefreshLoadView) {
    }
类似
![image](https://user-images.githubusercontent.com/19605922/62845568-b28e6380-bcfb-11e9-96b8-79dbebfe0fa0.png)
