### ISSUE TITLE
9.0系统 导航栏 有输入框的情况下 谈起或无法复位，有很大一片空白

### ISSUE THREAD

**Issue by CNleone** [AriesHoo/FastLib#39]
默认进入的时候位置没问题，点击输入框弹出键盘以后  导航栏的高度就变了  多了大概一个虚拟键的位置

**Comment by AriesHoo** [comment]
你是自己项目使用还是Demo就有问题？可否提供下图片

**Comment by AriesHoo** [comment]
我这边确认android 9.0正常的

**Comment by CNleone** [comment]
as 引入的2.2.13  然后用的 CommonTabLayout   加了个 InputMethodManager 弹出输入框  
监听的 CommonTabLayout    height 变256了  =。=

**Comment by CNleone** [comment]
9.0 以下没问题，9.0的一加和华为 带软导航的手机 出现这个问题

**Comment by AriesHoo** [comment]
那可能是之前版本BUG，两种方法
一、implementation 'com.github.AriesHoo.UIWidget:widget-core:3.2.19'
或者使用beta版本
implementation 'com.github.AriesHoo:FastLib:2.2.13_beta11'
还有就是如果使用了widget-core里面的软键盘处理就不要使用其它的InputMethodManager 因为会冲突

**Comment by AriesHoo** [comment]
你说这个情况和Android版本没有关系，有关系的是有导航栏的情况

**Comment by CNleone** [comment]
ok  感谢大佬   引入widget-core 解决了

**Comment by AriesHoo** [comment]
我是小菜鸟

**Comment by CNleone** [comment]
替换2.3.2以后 复现了，带导航栏的都有这个问题 用了widget-core也没用
