### ISSUE TITLE
加载进度条卡住不消失 

### ISSUE THREAD

**Issue by CNleone** [AriesHoo/FastLib#40]
使用的AgentWeb加载https路径 会卡在最后的位置。
https://github.com/Justson/AgentWeb/issues/618
大佬可以参考下

**Comment by AriesHoo** [comment]
你使用时候会出现卡住情况吗，我刚试了下没有卡住

**Comment by CNleone** [comment]
会卡住，用的你的WebViewActivity  可能有的机型有这个问题吧 
我的是一加7 和 华为p20  都能复现

**Comment by CNleone** [comment]
-，-  就是因为卡住了 找原因才发现agentweb 好几个关于这个的bug  issues

**Comment by CNleone** [comment]
就是因为卡住了 找原因才发现agentweb 好几个关于这个的bug  issues

**Comment by AriesHoo** [comment]
我看了下这个引起得原因是说得是如果获取WebView再setWebViewClient会覆盖AgentWeb 中的setWebViewClient方法，但是我的项目没有使用对应的setWebViewClient方法，我这里没有能复现的机子。那个解决方法在你那边能解决吗？
