### ISSUE TITLE
横版问题

### ISSUE THREAD

**Issue by CNleone** [AriesHoo/FastLib#42]
不支持平板使用吗  或者说 不支持切横屏？

**Comment by AriesHoo** [comment]
没有特别去注意横屏和平板，使用过程有什么问题？

**Comment by CNleone** [comment]
底部高度不对，头部宽度不对
用demo切横屏就可以复现 
UIWidget项目 我试了下   除了titlebarView 有这问题 其他是好的

**Comment by AriesHoo** [comment]
麻烦截图给我看看，我刚试了我手机横屏正常的

**Comment by CNleone** [comment]
![微信图片_20190826154401](https://user-images.githubusercontent.com/12593067/63674111-658cb000-c818-11e9-931b-4bc32fa1a8d3.jpg)

**Comment by AriesHoo** [comment]
那确实没有做这方面的适配。我大概看了下，因为ROM层改得太乱。没有找到合适方法判定导航栏所处的位置。故我放弃了。所以我在项目里都是固定竖屏得

**Comment by CNleone** [comment]
了解
