### ISSUE TITLE
请问下，怎么跳转到指定的主页面里

### ISSUE THREAD

**Issue by D-zy** [AriesHoo/FastLib#43]
博主，比如我在某个页面里，点击想跳转到主页中“我的”tab下，怎么设置啊

**Comment by D-zy** [comment]
使用 mTabLayout.setCurrentTab(2);  时，底部tab“我的”是选中了，但是viewPage 却显示的是“首页”的

**Comment by AriesHoo** [comment]
@Override
    public void setTabLayout(CommonTabLayout tabLayout) {
        mTabLayout = tabLayout;
    }

然后 切换Fragment
public void switchTabIndex(int index) {
        if (mTabLayout == null || mTabLayout.getCurrentTab() == index) {
            return;
        }
        mTabLayout.setCurrentTab(index);
    }

**Comment by AriesHoo** [comment]
FastLib使用的是哪个版本，用最新的。

**Comment by D-zy** [comment]
是用的比较新的版本，但这样设置了，还是无效

**Comment by AriesHoo** [comment]
用最新的，你说的那个问题我是知道的，是tabLayout里面Fragment的加载方式问题，我改过

**Comment by D-zy** [comment]
好的，更新了已解决，谢谢
