### ISSUE TITLE
请问：底部导航可以多样式吗

### ISSUE THREAD

**Issue by yueye410** [AriesHoo/FastLib#44]
这种样式，可以监听到中间➕的点击事件
图片链接：http://pics.lxpeng.net/303F678A-CBF3-4BD2-94D6-E70F14AAAB40.png

**Comment by AriesHoo** [comment]
这个不支持，抱歉

**Comment by AriesHoo** [comment]
这个库是根据之前 https://github.com/H07000223/FlycoTabLayout 进行部分优化修改，未进行功能扩展

**Comment by yueye410** [comment]
> 这个库是根据之前 https://github.com/H07000223/FlycoTabLayout 进行部分优化修改，未进行功能扩展

好的，谢谢。

**Comment by AriesHoo** [comment]
这个后面我会扩展。扩展好了通知你。如果你还用的话

**Comment by yueye410** [comment]
好的，谢谢

**Comment by AriesHoo** [comment]
暂时解决方案 
 @Override
    public void setTabLayout(CommonTabLayout tabLayout) {
        LinearLayout linearLayout = FindViewUtil.getTargetView(tabLayout,LinearLayout.class);
        if(linearLayout!=null){
            ViewGroup.MarginLayoutParams p0 = (ViewGroup.MarginLayoutParams) linearLayout.getChildAt(1).getLayoutParams();
            if(p0!=null){
                p0.rightMargin = SizeUtil.dp2px(40);
            }
            ViewGroup.MarginLayoutParams p1 = (ViewGroup.MarginLayoutParams) linearLayout.getChildAt(2).getLayoutParams();
            if(p1!=null){
                p1.leftMargin = SizeUtil.dp2px(40);
            }
        }
        FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        params.gravity = Gravity.CENTER;
        ImageView imageView = new ImageView(mContext);
        imageView.setImageResource(R.drawable.ic_launcher);
        tabLayout.addView(imageView,params);
    }

**Comment by AriesHoo** [comment]
使用2.3.0版本或者
implementation 'com.github.AriesHoo.UIWidget:tab-layout:3.2.23'
使用tabLayout.setCenterView 即可
