### ISSUE TITLE
替换2.3.2之后复现了，带导航栏的底部高度有问题，用了widget-core也没用

### ISSUE THREAD

**Issue by CNleone** [AriesHoo/FastLib#46]
如题

**Comment by CNleone** [comment]
[Uploading 复现视频.zip…]()

**Comment by AriesHoo** [comment]
![image](https://user-images.githubusercontent.com/19605922/67186093-dec01200-f419-11e9-8d02-bfb5512c3193.png)
将impl-ActivityControlImpl类里如下代码注释掉，当时测试后面push忘记注释了
