### ISSUE TITLE
将simpleEventbus替换后，启动应用就报its super classes have no public methods with the @Subscribe annotation

### ISSUE THREAD

**Issue by wangsong1991** [AriesHoo/FastLib#50]
这是什么原因，我用到eventbus的方法都用了权限public，所有用到的地方都出现这个问题，如果在该类中加上@Subscribe(threadMode = ThreadMode.MAIN)
    public void getEventBus(Integer integer) {}  就都不报错了，但是不能所有的都加这个呀，能给出个解决办法吗？网上都是让加注解+public，这些我都加了

**Comment by AriesHoo** [comment]
你是用的哪个版本？还有在最新的版本里eventbus没有被导入需要自己引入

**Comment by wangsong1991** [comment]
我知道  我用的2.3.4  我自己导入了eventbus，替换simple.evenbus后，就显示这个问题，不知道是我的原因还是说替换出错了，

**Comment by wangsong1991** [comment]
demo是没有问题的

**Comment by AriesHoo** [comment]
你是想用 org.greenrobot:eventbus:3.1.1 这个eventbus嘛

**Comment by wangsong1991** [comment]
对

**Comment by wangsong1991** [comment]
我看git上的用法 跟之前没有什么区别呀，所以我就替换了升级了一下版本

**Comment by AriesHoo** [comment]
你要在对应的Activity里定义public methods with the @Subscribe annotation 如图
![image](https://user-images.githubusercontent.com/19605922/70844116-56894680-1e77-11ea-93e3-179da008263c.png)
我之前一直用的是AndroidEventBus没实际弄过EventBus。后面版本会将 isEventBusEnable 默认返回false

**Comment by wangsong1991** [comment]
![image](https://user-images.githubusercontent.com/9698820/70844145-c1d31880-1e77-11ea-973d-d5120f92fe05.png)
哦  那就麻烦了我这里  用的地方不多，不用的地方那就数不过来了   那我先不用eventbus

**Comment by AriesHoo** [comment]
可以用AndroidEventBus先

**Comment by wangsong1991** [comment]
![image](https://user-images.githubusercontent.com/9698820/70844234-32c70000-1e79-11ea-8f72-480f48d108b6.png)   androideventbus不会受影响是吗？

**Comment by wangsong1991** [comment]
AndroidEventBus现在不维护了

**Comment by wangsong1991** [comment]
现在是2.3.2以上版本  添加依赖后就会出现在这个问题

**Comment by wangsong1991** [comment]
添加了androideventbus也不管用，该怎么弄？

**Comment by AriesHoo** [comment]
AndroidEventBus功能目前是够用了的。我项目里一直在用，添加了AndroidEventBus要去掉EventBus、归根到底
1、添加了EventBus的在所有的Activity添加public methods with the @subscribe annotation或者
2、不需要EventBus的Activity  isEventBusEnable返回false不执行注册操作即可
后续我将isEventBusEnable默认返回false

**Comment by AriesHoo** [comment]
2.3.5版本做了修复。可以用正常使用EventBus不做其它设置即可
