### ISSUE TITLE
状态栏问题

### ISSUE THREAD

**Issue by yueye410** [AriesHoo/FastLib#51]
不使用你那个fast_layout_title_bar的时候，内容顶到状态栏，设android:fitsSystemWindows="true"无效，是我哪里设置的问题吗？

**Comment by AriesHoo** [comment]
可参考模拟非FastLib三方库…沉浸效果实例

**Comment by yueye410** [comment]
我看你那个，android:fitsSystemWindows="false"，没看到别的设置，我设置这个无效；
我现在还是继承你那个activity，但是没法使用你的title_bar，就出现了这个问题，使用你那个title没问题

**Comment by AriesHoo** [comment]
如果参考示例解决不了，可设置TitleBarView高度为0，有对应的方法

**Comment by yueye410** [comment]
大佬果然牛逼，这思维厉害了，👍
