### ISSUE TITLE
软键盘会将布局顶上去，设置android:windowSoftInputMode不管用，是keyboardContral的缘故吗

### ISSUE THREAD

**Issue by wangsong1991** [AriesHoo/FastLib#52]

**Comment by wangsong1991** [comment]
在首页有搜索框会将底部的按钮顶上去

**Comment by AriesHoo** [comment]
![image](https://user-images.githubusercontent.com/19605922/72424804-86eb3a00-37c1-11ea-94ef-bd70d88d2cab.png)
NavigationViewHelper 有方法setControlBottomEditTextEnable用于设置是否控制软键盘效果的。默认true可将不用控制的Activity过滤掉。
