### ISSUE TITLE
下载apk方法失灵

### ISSUE THREAD

**Issue by wuwenlin** [AriesHoo/FastLib#54]
下载app，使用移动网络有时候失效，没有显示下载的通知栏

**Comment by AriesHoo** [comment]
1、蒲公英原项目被蒲公英官方删除数据，现已重新上传安装密码 1
2、GitHub上的apk下载一直比较慢这个是网站本身问题

**Comment by wuwenlin** [comment]
我是说集成你的框架，我们版本升级的时候，用移动网络下载app时有时是失效的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aries Hoo²⁰¹⁹"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 上午10:39
收件人:&nbsp;"AriesHoo/FastLib"<FastLib@noreply.github.com&gt;;
抄送:&nbsp;"莫失莫忘"<1731701838@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriesHoo/FastLib] 下载apk方法失灵 (#54)




1、蒲公英原项目被蒲公英官方删除数据，现已重新上传安装密码 1
 2、GitHub上的apk下载一直比较慢这个是网站本身问题

**Comment by AriesHoo** [comment]
你说的版本升级是app应用内升级？咋实现的。这个库只是将已有的retrofit和okhttp进行简单的统一处理并未修改过底层(我也没有能力去改)。故可能得自己找下这个有时是什么情况了。
