### ISSUE TITLE
BaseRecyclerViewAdapterHelper升级

### ISSUE THREAD

**Issue by Joslyn-Chen** [AriesHoo/FastLib#59]
BaseRecyclerViewAdapterHelper使用了3.0以上包名不对，
SmartRefreshLayout使用了2.0以上包名不对。

**Comment by AriesHoo** [comment]
我看看，升个级

**Comment by Joslyn-Chen** [comment]
BaseRecyclerViewAdapterHelper的3.0以上改动太大，我又退回去了，这兼容问题....

**Comment by AriesHoo** [comment]
我就是看你在那个库有回复。。还有其它问题吗？

**Comment by Joslyn-Chen** [comment]
暂时没有了

**Comment by 18856914956** [comment]
BaseRecyclerViewAdapterHelper使用了3.0以上包名不对，2.0以上不能用BaseNodeAdapter

**Comment by AriesHoo** [comment]
先本地module升级集成FastLib，近期会找个时间统一处理下升级版本库兼容性相关问题

**Comment by Xue-Zhou** [comment]
什么时候可以升级成功啊

**Comment by AriesHoo** [comment]
你先用module形式修改一下用着先，最近公司事情比较忙，快好了发自我的华为手机-------- 原始邮件 --------发件人： Xue-Zhou ***@***.***>日期： 2021年3月24日周三 17:59收件人： AriesHoo/FastLib ***@***.***>抄送： Aries Hoo²⁰²¹ ***@***.***>, Comment ***@***.***>主    题： Re: [AriesHoo/FastLib] BaseRecyclerViewAdapterHelper升级 (#59)

什么时候可以升级成功啊

**Comment by AriesHoo** [comment]
2.4.0版本升级了BaseRecyclerViewAdapterHelper 3.x及SmartRefreshLayout2.x    注意包名及api的变化
