### ISSUE TITLE
在不使用TitlerBar的情况下，无法沉浸式

### ISSUE THREAD

**Issue by HalyangDream** [AriesHoo/FastLib#60]
在不使用TitlerBar的情况下，布局无法延伸到状态栏，有解决方案吗？

**Comment by AriesHoo** [comment]
app/src/main/java/com/aries/library/fast/demo/module/main/sample/TestStatusActivity.java这个Activity演示了没有TitleBar的沉浸示例，解决不了你的问题吗？你的具体页面是咋样的？
