### ISSUE TITLE
在继承使用BaseQuickAdapter, adpter中的“正在加载中...”无法消失

### ISSUE THREAD

**Issue by HalyangDream** [AriesHoo/FastLib#61]
在继承使用BaseQuickAdapter, adpter中的“正在加载中...”无法消失

**Comment by AriesHoo** [comment]
这个问题也要在这个库里问么？

你在合适的时候触发关掉不就可以了嘛

**Comment by HalyangDream** [comment]
> 这个问题也要在这个库里问么？
> 
> 你在合适的时候触发关掉不就可以了嘛

我调用loadMoreComplete还是一直在

**Comment by AriesHoo** [comment]
正在加载中是哪个库的，就调用对应库的关掉就好嘛，load More Complete好像是adapter里面的发自我的华为手机-------- 原始邮件 --------发件人： HalyangDream <notifications@github.com>日期： 2020年7月7日周二 22:07收件人： AriesHoo/FastLib <FastLib@noreply.github.com>抄送： Aries Hoo²⁰¹⁹ <AriesHoo@126.com>, Comment <comment@noreply.github.com>主    题： Re: [AriesHoo/FastLib] 在继承使用BaseQuickAdapter, adpter中的“正在加载中...”无法消失 (#61)



这个问题也要在这个库里问么？

你在合适的时候触发关掉不就可以了嘛



我调用loadMoreComplete还是一直在
