### ISSUE TITLE
导航栏

### ISSUE THREAD

**Issue by HalyangDream** [AriesHoo/FastLib#62]
在做一个私聊界面遇到的问题,步骤：
1.当软键盘调起时，会遮挡部分底部的view；
2.软键盘收起时，这部分被遮挡的view就消失了，应该时被导航栏遮挡了;
3.软键盘无法顶起最底部的view;
望大佬，告诉一下，关于软件盘弹出的控制

**Comment by AriesHoo** [comment]
demo中有个输入框例子是否也会出现？

**Comment by HalyangDream** [comment]
> demo中有个输入框例子是否也会出现？

demo中没有出现，因为使用情况不一样

**Comment by AriesHoo** [comment]
推荐使用这个专门处理软键盘的库 https://github.com/YummyLau/PanelSwitchHelper
