### ISSUE TITLE
底部导航栏适配问题

### ISSUE THREAD

**Issue by minveYu** [AriesHoo/FastLib#63]
试了下demo，现在很多新出的手机demo，底部都会留白，就是导航栏隐藏了，没有去适配，麻烦作者能解决一下

**Comment by AriesHoo** [comment]
都是哪些手机测试出现了，麻烦告知下

**Comment by minveYu** [comment]
一加，三星s20+,感觉就是全面屏手势的那些手机

**Comment by minveYu** [comment]
我还有一个疑惑，为什么Lifecyclecallback -setStatusbar 哪里 判断是FastMainActivity 就不处理，因为我自己activity是没有title的，底部也是导航栏，继承了BasisActivity，但是会增加了一个假性的状态栏占位，所以我不得不到布局里加一个Titlebar，就没问题

**Comment by Xue-Zhou** [comment]
全面屏手机 底部导航栏留白，软键盘收起时，底部view 就看不见了，继承类FastMainActivity的类也有此类问题，（一加六手机），希望尽快解决
![Screenshot_20210225-175621](https://user-images.githubusercontent.com/32625233/109137045-bc6ba080-7793-11eb-9455-9a53bff5fb7d.jpg)
![Screenshot_20210225-175934](https://user-images.githubusercontent.com/32625233/109137062-c2fa1800-7793-11eb-8167-c2d220a5f416.jpg)
![Screenshot_20210225-180014](https://user-images.githubusercontent.com/32625233/109137106-cf7e7080-7793-11eb-8ccf-c34d73ada009.jpg)
![Screenshot_20210225-180020](https://user-images.githubusercontent.com/32625233/109137128-d5745180-7793-11eb-8b87-2f10c84f72d1.jpg)

**Comment by AriesHoo** [comment]
现在全面屏手机很多，导航栏功能需求度不高了，适配太难
public boolean setNavigationBar(Activity activity, NavigationViewHelper helper, View bottomView) {
return false;
}
![image](https://user-images.githubusercontent.com/19605922/109413522-dbaf3b80-79e8-11eb-9db3-c75934d3aac4.png)
设置返回false不控制导航栏；

**Comment by AriesHoo** [comment]
如果实在想控制底部导航栏。建议直接给底部导航栏着色，可 .setPlusNavigationViewEnable(true)只使用一个参数的。注释掉多参数代码
public boolean setNavigationBar(Activity activity, NavigationViewHelper helper, View bottomView) {

        Activity previous = FastStackUtil.getInstance().getPrevious();
        boolean enable = previous != null && previous instanceof SwipeBackActivity;
        //其它默认属性请参考FastLifecycleCallbacks
        helper.setLogEnable(BuildConfig.DEBUG)
                .setPlusNavigationViewEnable(true)
                //此处为配合BGASwipeBackHelper滑动返回效果-如不使用BGASwipeBackHelper推荐使用上面的方法
//                .setPlusNavigationViewEnable(true, enable, enable)
        return true;
    }
