### ISSUE TITLE
我新建项目后拷贝出template代码，然后继承了下IFastRefreshView后和在你给的template中继承IFastRefreshView显示不一样

### ISSUE THREAD

**Issue by systemChina** [AriesHoo/FastLib#64]
求告知。。。
demo中的template运行是下拉转圈的效果
自己拷出来显示的是下拉可以刷新的文件

**Comment by systemChina** [comment]
![image](https://user-images.githubusercontent.com/18650479/92574843-37123380-f2ba-11ea-9afa-050115009a94.png)
都是这么写的。。。在template里面是下拉转圈的效果 ，在我的里头就变成下拉刷新带文字的那种，就是整个页面跟着下移的那种

**Comment by AriesHoo** [comment]
你看下wiki有没有可以解决你的问题的。https://github.com/AriesHoo/FastLib/wiki#225-%E4%B8%8B%E6%8B%89%E5%88%B7%E6%96%B0%E5%A4%B4smartrefreshlayout%E8%AE%BE%E7%BD%AE 还有多对比下你和demo的差异

**Comment by systemChina** [comment]
嘿。。。这么快就有回复，真是灰常感谢大佬。

**Comment by systemChina** [comment]
![image](https://user-images.githubusercontent.com/18650479/92579498-d71e8b80-f2bf-11ea-85de-1d1a8abb65ed.png)
我弄进去为啥是这样。。。应该是下拉转圈的那个
我是纯粹复制template里头的东西到新建项目中的。。。

**Comment by systemChina** [comment]
还有就是顶部的文字是会向下跟着滑动，而template中的转圈那种就不会

**Comment by systemChina** [comment]
@Override
    public void setRefreshLayout(SmartRefreshLayout refreshLayout) {
        int statusHeight = StatusBarUtil.getStatusBarHeight() + getResources().getDimensionPixelSize(R.dimen.dp_title_height);
        LoggerManager.i("statusHeight:" + statusHeight + ";dp:" + SizeUtil.px2dp(statusHeight));
        refreshLayout.setHeaderInsetStart(SizeUtil.px2dp(statusHeight));
    }
是因为这个。。。template中也加了这个的。我去掉这个就好了，，，以后有空了再看看原因吧

**Comment by iSally** [comment]
重写 DefaultRefreshHeaderCreator 中的 createRefreshHeader 就可以了啊

**Comment by Xue-Zhou** [comment]
问题一：从不同地方跳转activity，activity 继承 FastTitleActivity 实现 IFastRefreshView （extends FastTitleActivity implements IFastRefreshView），有时候标题栏 不显示
![image](https://user-images.githubusercontent.com/32625233/113848862-7ad70800-97cb-11eb-9493-765d60c128b1.png)
![image](https://user-images.githubusercontent.com/32625233/113848896-84f90680-97cb-11eb-8b26-e554f1cfcc6b.png)

还有右上角标题 利用 addRightAction 添加布局，设置宽度，间距都不起作用

问题二：我在当前activity页面，activity 继承 FastTitleActivity 实现 IFastRefreshView （extends FastTitleActivity implements IFastRefreshView），怎么才能获取到 布局管理器StatusManager，进行状态管理

**Comment by AriesHoo** [comment]
问题一：demo中有类似的Activity出现过类似问题没有，标题栏是一个view  fastlib没有控制过其显示隐藏
问题二：addRightAction本质是在右边的layout添加子view  设置宽高和动态代码设置一样一样的这个自己可以处理，你可以titleBar.getLinearLayout(Gravity.RIGHT) 获取到右边layout再addView即可
问题三：可进入IFastRefreshView这个接口是实现下拉刷新的，你可以进去看看是没有多状态布局相关的。所以也不存在可以获取StatusManager的管理器
如果要单独实现多状态布局也很方便。参考FastRefreshLoadDelegate 类 setStatusManager方法。很简单的
