### ISSUE TITLE
三星A90导航条设置为全屏手势时底部导航也会出现空白

### ISSUE THREAD

**Issue by dragonhn** [AriesHoo/FastLib#65]
![Screenshot_20201027-094742](https://user-images.githubusercontent.com/12883451/97247001-b2638080-1839-11eb-9ee2-594d09ac804d.jpg)

**Comment by dragonhn** [comment]
![Screenshot_20201027-094742](https://user-images.githubusercontent.com/12883451/97247229-3f0e3e80-183a-11eb-8f8e-b0781fe5efa7.jpg)

**Comment by AriesHoo** [comment]
将ActivityControlImpl 的 setNavigationBar 返回值设置为false

**Comment by dragonhn** [comment]
好的，谢谢
