### ISSUE TITLE
FastWebActivity好像无法加载本地html文件

### ISSUE THREAD

**Issue by systemChina** [AriesHoo/FastLib#66]
if (!TextUtils.isEmpty(mUrl)) {
            mUrl = mUrl.startsWith("http") ? mUrl : "http://" + mUrl;
            getIntent().putExtra("url", mUrl);
        }
是不是可以改一下

**Comment by AriesHoo** [comment]
2.4.0微调了一下。。AgentWeb没有直接暴露loadData接口。
1、 mAgentWeb.getWebCreator().getWebView()   获取webView自己loadData
2、mAgentWeb.getUrlLoader().loadData();   

以上两种操作均可解决问题
