### ISSUE TITLE
多次调用loadData

### ISSUE THREAD

**Issue by Xue-Zhou** [AriesHoo/FastLib#75]
继承FastRefreshLoadActivity的activity第一次进入会多次调用loadData

**Comment by AriesHoo** [comment]
你是怎么操作的。如图所示
![image](https://user-images.githubusercontent.com/19605922/106975284-34483b80-6791-11eb-85d6-b8cc63266e02.png)
module->mine->ThirdLibraryActivity  我在loadData打印了一个error 类型的进去只调用了一次

**Comment by Xue-Zhou** [comment]
不记得怎么操作了，好像是多层fragment嵌套导致的问题
