### ISSUE TITLE
初始化失败，无法调用，配置文件修改不起作用

### ISSUE THREAD

**Issue by Xue-Zhou** [AriesHoo/FastLib#76]
FastManager.init(this); 无法初始化，
提示错误: init(Application)在FastManager中不是公共的; 无法从外部程序包中对其进行访问
如图
![image](https://user-images.githubusercontent.com/32625233/108580861-68faec00-7368-11eb-9321-00d30c6afc8b.png)
![image](https://user-images.githubusercontent.com/32625233/108580869-6f896380-7368-11eb-8072-ee2cc0b9e9dd.png)

使用自定义初始化方法，修改fast_color.xml文件，部分属性相关连不起作用，指向的是修改后的colorTitleText文字颜色
如图
![image](https://user-images.githubusercontent.com/32625233/108580936-b5dec280-7368-11eb-9360-d76e8006ea05.png)
![image](https://user-images.githubusercontent.com/32625233/108580945-c7c06580-7368-11eb-89e7-2483e8f899e5.png)

不修改fast_color.xml配置文件，代码中修改颜色也不起作用，调用的还是fast_color.xml中的配置
如图
![image](https://user-images.githubusercontent.com/32625233/108581055-57feaa80-7369-11eb-9eaa-ca5e26007f38.png)
![image](https://user-images.githubusercontent.com/32625233/108581061-61881280-7369-11eb-8ff4-59687e61f5e8.png)
![image](https://user-images.githubusercontent.com/32625233/108581076-82506800-7369-11eb-865e-eec8905d473f.png)

还有，希望尽快升级adapter等版本

**Comment by AriesHoo** [comment]
1、init()方法可以不用调用了，库内部初始化
2、问题二确实我库里设置里设置里默认颜色导致配置xml不生效，可通过AppImpl 里setMultiStatusView 设置下，下个版本修改
@Override
    public void setMultiStatusView(StatusLayoutManager.Builder statusView, IFastRefreshLoadView iFastRefreshLoadView) {
        statusView.setDefaultEmptyClickViewTextColor(ContextCompat.getColor(mContext, R.color.status_layout_click_view_text_color))
                .setDefaultErrorClickViewTextColor(ContextCompat.getColor(mContext, R.color.status_layout_click_view_text_color));

    }
![image](https://user-images.githubusercontent.com/19605922/108582924-1c67de80-7371-11eb-977d-df355ff883c0.png)

3、在做整理升级三方库及豆瓣Api失效问题处理

**Comment by AriesHoo** [comment]
2.4.0版本做了升级-注意api变化
