### ISSUE TITLE
多布局适配器

### ISSUE THREAD

**Issue by Xue-Zhou** [AriesHoo/FastLib#77]
请问 继承 FastRefreshLoadFragment 或者 FastRefreshLoadActivity的页面 怎么使用 多布局适配器BaseMultiItemQuickAdapter

**Comment by AriesHoo** [comment]
![image](https://user-images.githubusercontent.com/19605922/108943569-108f5b80-7694-11eb-9fe7-b552bed7fddc.png)
在回调
    @Override
    public BaseQuickAdapter<WidgetEntity, BaseViewHolder> getAdapter() {
return  new XXAdapter()
}
这个XXAdapter extends BaseMultiItemQuickAdapter即可
