### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dmool.anime/com.kuaikan.comic.reader.ui.ComicDetailActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by lidynast** [AriesHoo/FastLib#78]
![image](https://user-images.githubusercontent.com/9794965/112275571-b8f80600-8cba-11eb-8877-3372d75b0703.png)
上面这句代码会导，下图写法的activity崩溃
![image](https://user-images.githubusercontent.com/9794965/112275734-db8a1f00-8cba-11eb-9c62-0fbd791281c0.png)
下面错误日志
![image](https://user-images.githubusercontent.com/9794965/112276119-4e939580-8cbb-11eb-9462-5baaa0826ee5.png)

**Comment by lidynast** [comment]
准确的谁是后面那个代码：FastUtil.getRootView(activity)

**Comment by AriesHoo** [comment]
从你的错误日志来看没看出是指向FastLib的某个类的问题，你是如何确定的？
从你错误日志来看是你requestWindowFeature的调用时机的问题？
你再确认下

**Comment by lidynast** [comment]
问题我已经解决了，我把Fastlib用module引入方式，然后去掉那句日志打印就可以了
requestWindowFeature这个句代码是我接入一个SDK里面的Activity中使用的，没办法去修改

**Comment by AriesHoo** [comment]
解决了就好发自我的华为手机-------- 原始邮件 --------发件人： lidynast ***@***.***>日期： 2021年3月24日周三 17:48收件人： AriesHoo/FastLib ***@***.***>抄送： Aries Hoo²⁰²¹ ***@***.***>, State change ***@***.***>主    题： Re: [AriesHoo/FastLib] java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dmool.anime/com.kuaikan.comic.reader.ui.ComicDetailActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content (#78)

问题我已经解决了，我把Fastlib用module引入方式，然后去掉那句日志打印就可以了

requestWindowFeature这个句代码是我接入一个SDK里面的Activity中使用的，没办法去修改
