### ISSUE TITLE
请求头

### ISSUE THREAD

**Issue by Xue-Zhou** [AriesHoo/FastLib#79]
登录时会返回一个参数作为公共请求头，退出时在清空，请问怎么才能做到实时更新？

**Comment by AriesHoo** [comment]
![image](https://user-images.githubusercontent.com/19605922/112777608-3930b980-9075-11eb-812a-dac4dff1e00b.png)
在适当的时机  FastRetrofit.getInstance().addHeader(key,value)   不用的时候FastRetrofit.getInstance().removeHeader(key)

**Comment by Xue-Zhou** [comment]
谢谢，我后来改好了，开始我是写在application里面的，之前添加的公共参数拦截器会更新，就以为请求头也能
