### ISSUE TITLE
网络请求

### ISSUE THREAD

**Issue by bing27** [AriesHoo/FastLib#8]
博主，这个项目网络框架可以详细些么，比如多写几个案例，登录之类啊，感觉扩展有些麻烦

**Comment by AriesHoo** [comment]
一、首先这个库是基于RaJava和Retrofit和Okhttp的  所以必须有相关的知识储备
二、库里面封装得retrofit包下就是快速实现的部分功能
三、你说的登录问题是遇到了什么样的具体问题，你描述清楚我才好具体给你分析
