### ISSUE TITLE
eventbus 使用

### ISSUE THREAD

**Issue by yanshangluobai** [AriesHoo/FastLib#80]
FastLib:2.4.0版本导入 implementation 'org.greenrobot:eventbus:3.2.0'，eventbus 事件接受不到
![image](https://user-images.githubusercontent.com/32625233/120153598-80782980-c221-11eb-93d5-a0885ff7b46d.png)

**Comment by AriesHoo** [comment]
这个eventBus传递事件貌似不是你这种写法 https://github.com/greenrobot/EventBus

**Comment by AriesHoo** [comment]
我刚按照EventBus官网说明测试了下，正常的，你参考官网测试下，FastLib只做了EventBus初始化

**Comment by Xue-Zhou** [comment]
我换成了androidEventBus，post可以接收到事件，postSticky就接收不到，两者接收方法有什么不同吗？使用的默认的tag
![image](https://user-images.githubusercontent.com/32625233/120171426-9e9b5500-c234-11eb-9f63-77033fcd7a29.png)



eventbus 大概不能直接传递数据，只能用类传递
