### ISSUE TITLE
标题栏不显示

### ISSUE THREAD

**Issue by yanshangluobai** [AriesHoo/FastLib#81]
继承 FastTitleActivity，从不同入口进入同一个页面，开始都是正常的，程序崩溃过几次后，一个显示正常，另一个标题栏突然不显示了，断点 发现 setTitleBar 没有执行，这种情况是 为什么，不是第一次出现
![image](https://user-images.githubusercontent.com/32625233/120289331-c56c9080-c2f3-11eb-9583-ffaaace8dcbf.png)

![image](https://user-images.githubusercontent.com/32625233/120289302-bab1fb80-c2f3-11eb-95db-14b5768d42ac.png)

**Comment by AriesHoo** [comment]
1、是如何造成崩溃的，是fastlib内部造成的还是程序本身，fastLib造成的麻烦提供下日志，感谢，如果是程序本身造成就解决下程序问题
2、如果是fastLib造成的，能否提供一个能重现的demo

**Comment by yanshangluobai** [comment]
程序本身造成的崩溃，空指针异常，就是后来改好之后，测试的时候想点返回，就发现标题栏不显示了，我改成继承IFastTitleView方式也是一样，其他的都没有问题。

**Comment by yanshangluobai** [comment]
程序本身造成的崩溃，空指针异常，就是后来改好之后，测试的时候想点返回，就发现标题栏不显示了，我改成继承IFastTitleView方式也是一样，其他的都没有问题。
