### ISSUE TITLE
返回按钮无效

### ISSUE THREAD

**Issue by yanshangluobai** [AriesHoo/FastLib#83]
2.4.0版本，继承FastTitleActivity，点击返回键，有时候有效果，有时候没效果，断点发现执行了相关关闭代码（activity.finish()），但是页面未关闭，代码没起作用
![image](https://user-images.githubusercontent.com/32625233/123936146-7f285100-d9c7-11eb-83e3-2ac0cb5ea2bc.png)

**Comment by AriesHoo** [comment]
如果统一处理不行就在对应的Activity 自己设置下关闭方法
