### ISSUE TITLE
onVisibleChanged重复执行

### ISSUE THREAD

**Issue by yanshangluobai** [AriesHoo/FastLib#84]
主页面 MainActivity 继承 FastMainActivity，fragment onVisibleChanged方法不知道为什么突然间不停执行
![image](https://user-images.githubusercontent.com/32625233/124538214-d4dc7d80-de4d-11eb-800a-79bd7bda3958.png)

**Comment by yanshangluobai** [comment]
我今天又把代码放开尝试了一次，突然就好了，为什么会出现这种情况？
![image](https://user-images.githubusercontent.com/32625233/124689877-e5532d80-df0b-11eb-84a2-3436b34c4c69.png)

**Comment by AriesHoo** [comment]
这个确实不清楚你那边咋操作的，没出现就好，遇到问题先试一试demo
