### ISSUE TITLE
retrofit2.adapter.rxjava2.HttpException: HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by bing27** [AriesHoo/FastLib#9]
private FastRetrofit() {
        sClientBuilder = new OkHttpClient.Builder();
        _**sClientBuilder.sslSocketFactory(MySSLSocketFactory.getSSLSocketFactory())
                .hostnameVerifier(new HostnameVerifier() {
                    @Override
                    public boolean verify(String hostname, SSLSession session) {
                        HostnameVerifier hv = HttpsURLConnection.getDefaultHostnameVerifier();
                        return hv.verify("app.91q.com", session);
                    }
                })
                .addInterceptor(mHeaderInterceptor).build();**_
        sRetrofitBuilder = new Retrofit.Builder()
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create());
        setTimeout(mDelayTime);
        FastMultiUrl.getInstance().with(sClientBuilder);
    }

**Comment by AriesHoo** [comment]
这个是是配置Okhttp的问题吧。

**Comment by AriesHoo** [comment]
retrofit和Okhttp配置相关的可自行百度的
